name: MiyabiDash
options:
  bundleIdPrefix: com.miyabi
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""  # Set your team ID
    SWIFT_VERSION: "5.9"

targets:
  MiyabiDash:
    type: application
    platform: iOS
    sources:
      - MiyabiDash
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "Miyabi 🌸"
        PRODUCT_BUNDLE_IDENTIFIER: com.miyabi.dash
    entitlements:
      path: MiyabiDash/MiyabiDash.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.miyabi.dash

  MiyabiDashWidget:
    type: app-extension
    platform: iOS
    sources:
      - MiyabiDashWidget
      - path: MiyabiDash/Models
        group: Shared
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: "Miyabi Widget"
        INFOPLIST_KEY_NSWidgetWantsLocation: false
        PRODUCT_BUNDLE_IDENTIFIER: com.miyabi.dash.widget
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: MiyabiDashWidget/MiyabiDashWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.miyabi.dash
    dependencies:
      - target: MiyabiDash
        embed: false
